---
title: "R Notebook"
output: html_notebook
---


```{r}
library(data.table)
```
```{r}
new <- fread("C:/Users/schadem/Box Sync/LAPOP Shared/working documents/maita/Coordination/Noam Argentina Panel/Matching process/Data/AR/panel/190910/VANDUS 1147438_W3_20190906.csv")
```


```{r}
old <- fread("C:/Users/schadem/Box Sync/LAPOP Shared/working documents/maita/Coordination/IDB Online/Matching process/Data/All countries export/20190628/VANDUS_1147438_w2_20190628.csv")

old.depto <- old[Negate(is.na)(AR_departamento),]
old.prov <- old[Negate(is.na)(AR_provincia)]
```

```{r}
hist(old.depto$AR_departamento, nclass=dim(table(old.depto$AR_departamento)))
```
```{r}
hist(new$AR_departamento, nclass=dim(table(new$AR_departamento)))
```

What is going on with the bizarre missingness of CABA in the final dataset?
```{r}
sort(table(new$AR_provincia), decreasing = T)
sort(table(old.depto$AR_provincia), decreasing = T)
sort(table(old.prov$AR_provincia), decreasing = T)
old.prov[AR_provincia==1,AR_departamento]
```

In full panel, have enough of CABA. When did the problem happen?
```{r}
old.ar_only <- fread("C:/Users/schadem/Box Sync/LAPOP Shared/working documents/maita/Coordination/IDB Online/Matching process/Data/AR/panel/AR_netquest-panel.csv")
old.geo <- fread("C:/Users/schadem/Box Sync/LAPOP Shared/working documents/maita/Coordination/IDB Online/Matching process/Data/AR/panel/AR_netquest-panel_geo.csv")
dim(old.ar_only)
dim(old.geo)
dim(old.prov)
```
It doesn't seem like the panel_geo was drastically reduced... what do its vars look like?
```{r}
sort(table(old.ar_only$AR_provincia),decreasing = T)
sort(table(old.geo$AR_provincia),decreasing = T)
old.geo[AR_provincia==1,X]
```


```{r}
sort(table(new$AR_departamento), decreasing = T)[1:20]
sort(table(old$AR_departamento), decreasing = T)[1:30]
```


```{r}
hist(old$AR_provincia, nclass = 24)
dim(table(old$AR_provincia))
```


```{r}
hist(new$AR_provincia, nclass=24)
dim(table(new$AR_provincia))
```

